
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: appdb
      JWT_SECRET: super_secret_key
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
